---
inherit_gem:
  voxpupuli-test: rubocop.yml
require:
  - rubocop-rspec
  - rubocop-rake
AllCops:
  TargetRubyVersion: '3.2'
Layout/DotPosition:
  EnforcedStyle: leading
Style/CommentedKeyword:
  Enabled: false
Naming/FileName:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/BeforeAfterAll:
  Enabled: false
