---
easy_ipa::ipa_master_fqdn: "ipa1.ls.lsst.org"
rsyslog::config::actions:
# Send copy to logs to Ruka Cluster
  graylogCloud:
    type: "omfwd"
    facility: "*.*"
    config:
      Target: "collector.lsst.cloud"
      Port: 5514
      Protocol: "udp"
# Send copy to logs to Base Graylog instance
  graylogBase:
    type: "omfwd"
    facility: "*.*"
    config:
      Target: "collector.ls.lsst.org"
      Port: 5514
      Protocol: "udp"
# Send copy to logs to Summit Graylog instance
  graylogSummit:
    type: "omfwd"
    facility: "*.*"
    config:
      Target: "collector.cp.lsst.org"
      Port: 5514
      Protocol: "udp"
  # Don't log private authentication messages!
  #
  # local6 is used for logs that should only be forwarded to a central log
  # server and should never be stored locally. See IT-1734.
  # Log anything (except mail) of level info or higher.
  # Don't log private authentication messages!
  #
  # local6 is used for logs that should only be forwarded to a central log
  # server and should never be stored locally. See IT-1734.
  messages:
    type: "omfile"
    facility: "*.info;mail.none;authpriv.none;cron.none;local6.none"
    config:
      file: "/var/log/messages"
  # The authpriv file has restricted access.
  secure:
    type: "omfile"
    facility: "authpriv.*"
    config:
      file: "/var/log/secure"
  # Everybody gets emergency messages
  emerg:
    type: "omusrmsg"
    facility: "*.emerg"
    config:
      users: "*"
  maillog:
    type: "omfile"
    facility: "mail.*"
    config:
      file: "-/var/log/maillog"
  cron:
    type: "omfile"
    facility: "cron.*"
    config:
      file: "/var/log/cron"
  # local7 does not appear to be used by CentOS 7, but for the sake of
  # consistency we preserve it to match the CentOS configuration.
  boot:
    type: "omfile"
    facility: "local7.*"
    config:
      file: "-/var/log/boot.log"
# The following keys are shared between the `dhcp` and `resolv_conf` classes:
# - dhcp::dnsdomain
# - dhcp::nameservers
# - dhcp::ntpservers
#
# @see site/ls/role/foreman.yaml

# resolv.conf allows for a maximum of 6 search domains with a max length of 256
# characters.
# @see man 5 resolv.conf
dhcp::dnsdomain: &dnsdomains
  - "dev.lsst.org"
  - "ls.lsst.org"
  - "lsst.org"
# resolv.conf allows for a maximum of 3 nameservers
# @see man 5 resolv.conf
dhcp::nameservers: &nameservers
  - "139.229.134.53"  # dns1.dev.lsst.org
  - "139.229.134.54"  # dns2.dev.lsst.org
  - "139.229.134.55"  # dns3.dev.lsst.org
dhcp::ntpservers: &ntpservers
  - "ntp.shoa.cl"
  - "ntp.cp.lsst.org"
  - "1.cl.pool.ntp.org"
  - "1.south-america.pool.ntp.org"

chrony::servers: *ntpservers
ntp::servers: *ntpservers
resolv_conf::nameservers: *nameservers
resolv_conf::searchpath: *dnsdomains

accounts::user_list:
  root:
    purge_sshkeys: true
    sshkeys:
      # foreman-proxy
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIAmA8aQ9Qf8ok+zPUSwFWfEgNxUW1RptUhZE9/9PFGzhAi7XMnt6qaSFINlLxiECUXKeK3iwHI3rLxMsJpcGRGkkL9GGpUYNgyDVZt82AFN2rt7nvuYqm9M7M4Q6NeLlMEGUf9iSnzE/IpT4459iOiKdaB3SifuXWjJeUSOoNACugJcQCZm4nQGo9ZUVJcbhYael++pcobApctOOFjlaVi6s+iB4qdidMJ9CUEyQ8HBSDomBnj2dZ5QB/bDHUW1OKo/i+LbMdF1HrnEcI9AkSHfkW+OP7L5mkmRJBNsK5R6YzIb41LHCvO1Fvoinb71JkWD5ElzTLY5e7YkjRXkQV foreman-proxy@foreman.dev.lsst.org"

letsencrypt::server: "https://acme-staging.api.letsencrypt.org/directory"  # testing url
profile::core::common::disable_ipv6: true
profile::core::monitoring::url: "http://it-influxdb.ls.lsst.org:8086"
