---
easy_ipa::ipa_master_fqdn: "ipa1.dev.lsst.org"

rsyslog::config::actions:
#Send copy to logs to Base Graylog instance
  graylogBase:
    type: "omfwd"
    facility: "*.*;auth,authpriv.none"
    config:
      Target: "graylog.ls.lsst.org"
      Port: 5514
      Protocol: "udp"
  #Send copy to logs to Summit's Graylog instance
  graylogSummit:
    type: "omfwd"
    facility: "*.*;auth,authpriv.none"
    config:
      Target: "graylog.cp.lsst.org"
      Port: 5514
      Protocol: "udp"
  # Log anything (except mail) of level info or higher.
  # Don't log private authentication messages!
  #
  # local6 is used for logs that should only be forwarded to a central log
  # server and should never be stored locally. See IT-1734.
  messages:
    type: "omfile"
    facility: "*.info;mail.none;authpriv.none;cron.none;local6.none"
    config:
      file: "/var/log/messages"
  # The authpriv file has restricted access.
  secure:
    type: "omfile"
    facility: "authpriv.*"
    config:
      file: "/var/log/secure"
  # Everybody gets emergency messages
  emerg:
    type: "omusrmsg"
    facility: "*.emerg"
    config:
      users: "*"
  maillog:
    type: "omfile"
    facility: "mail.*"
    config:
      file: "-/var/log/maillog"
  cron:
    type: "omfile"
    facility: "cron.*"
    config:
      file: "/var/log/cron"
  # local7 does not appear to be used by CentOS 7, but for the sake of
  # consistency we preserve it to match the CentOS configuration.
  boot:
    type: "omfile"
    facility: "local7.*"
    config:
      file: "-/var/log/boot.log"

# Telegraf common configuration
telegraf::global_tags:
  service: "%{::service}"
  cluster: "%{::cluster}"
  device: "%{::device}"
  service_number: "%{::service_number}"
  device_number: "%{::device_number}"
  node_name: "%{::node_name}"
  datacenter: "%{::datacenter}"
  type: "%{::virtual}"
telegraf::interval: "1m"
telegraf::round_interval: true
telegraf::metric_batch_size: 1000
telegraf::metric_buffer_limit: 10000
telegraf::collection_jitter: "0s"
telegraf::flush_interval: "1m"
telegraf::flush_jitter: "0m"
telegraf::debug: false
telegraf::quiet: false
telegraf::hostname: ""
telegraf::omit_hostname: false

# The following keys are shared between the `dhcp` and `resolv_conf` classes:
# - dhcp::dnsdomain
# - dhcp::nameservers
# - dhcp::ntpservers
#
# @see clusters/corecp/dhcp.yaml

# resolv.conf allows for a maximum of 6 search domains with a max length of 256
# characters.
# @see man 5 resolv.conf
dhcp::dnsdomain: &dnsdomains
  - "cp.lsst.org"
  - "cp.cl.lsst.org"
  - "cl.lsst.org"
  - "dev.lsst.org"
  - "lsst.org"
  - "lsst.local"
# resolv.conf allows for a maximum of 3 nameservers
# @see man 5 resolv.conf
dhcp::nameservers: &nameservers
  - "139.229.134.7"  # dns1.dev.lsst.org
  - "139.229.136.35"  # pihole.lsst.local
  - "208.67.222.222"  # resolver1.opendns.com
dhcp::ntpservers: &ntpservers
  - "ntp.cp.lsst.org"
  - "ntp.shoa.cl"
  - "1.cl.pool.ntp.org"
  - "1.south-america.pool.ntp.org"

chrony::servers: *ntpservers
resolv_conf::nameservers: *nameservers
resolv_conf::searchpath: *dnsdomains
# Use NFSv4 on NFS enabled hosts.
# @see site/cp/role/nfsserver.yaml
nfs::nfs_v4: true
nfs::nfs_v4_client: true
nfs::nfs_v4_idmap_domain: "%{::domain}"
