---
# yamllint disable rule:quoted-strings
name: Commit Message Check

"on": pull_request

jobs:
  preflight:
    runs-on: ubuntu-latest
    outputs:
      renovate: ${{ steps.renovate.outputs.renovate }}
    steps:
      # flag PRs opened by renovate
      - id: renovate
        run: |
          if [[ ${{ github.head_ref }} == *"renovate"* ]]; then
             echo "renovate=true" >> $GITHUB_OUTPUT
          else
             echo "renovate=false" >> $GITHUB_OUTPUT
          fi

  check-commit-message:
    name: Check Commit Message
    needs: [preflight]
    # ignore PRs from renovate
    if: ${{ needs.preflight.outputs.renovate }} == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '\([^)]+\) .+$'
          flags: gm
          error: Your first line has to contain a commit type like '(role/foo)'.
          checkAllCommitMessages: "true"
          accessToken: "${{ secrets.GITHUB_TOKEN }}"
      - name: Check Line Length
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^(?!.{73})'
          error: The maximum line length of 72 characters is exceeded.
          checkAllCommitMessages: "true"
          accessToken: "${{ secrets.GITHUB_TOKEN }}"
