---
# yamllint disable rule:quoted-strings
name: librarian-puppet

"on":
  push:
    branches:
      - production
      - cp_production
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  librarian_puppet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.5
      - run: bundle install
      - name: Puppetfile recursive dependency check
        run: |
          echo "exclusion 'choria-mcollective'" >> Puppetfile
          bundle exec librarian-puppet install --verbose
