---
# yamllint disable rule:quoted-strings
name: librarian-puppet

"on":
  push:
    branches:
      - production
      - cp_production
  pull_request:

jobs:
  librarian_puppet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.7
      - run: bundle install
      - name: Puppetfile recursive dependency check
        run: bundle exec librarian-puppet install --verbose
