---
# yamllint disable rule:quoted-strings
name: markdownlint

"on":
  push:
    branches:
      - production
      - cp_production
  pull_request:

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run mdl
        uses: actionshub/markdownlint@main
