---
name: "Pull Request Labels"
"on":
  pull_request:
    types: ["opened", "labeled", "unlabeled", "synchronize"]
jobs:
  label:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "mheap/github-action-required-labels@v3"
        with:
          mode: "exactly"
          count: 1
          labels: "enhancement, bug, skip-changelog"
          add_comment: true
          message: "This PR is being prevented from merging because of missing or incorrect labels."
